"""Text extraction and chunking public API."""

from .core import (
    DEFAULT_MAX_CHUNK_TOKENS,
    LEGACY_FORMAT_REASON,
    SCANNED_PDF_OCR_REASON,
    SUPPORTED_TEXT_EXTENSIONS,
    TEXT_EXTRACTION_CATEGORIES,
    ChunkRecord,
    ExtractedDocument,
    ExtractionError,
    ExtractionFailure,
    ExtractionFailureSummary,
    ExtractionRunResult,
    ExtractionStatus,
    PendingFileRecord,
    RawChunk,
    extract_file,
    extract_pending_files,
    load_extraction_status,
)

__all__ = [
    "DEFAULT_MAX_CHUNK_TOKENS",
    "LEGACY_FORMAT_REASON",
    "SCANNED_PDF_OCR_REASON",
    "SUPPORTED_TEXT_EXTENSIONS",
    "TEXT_EXTRACTION_CATEGORIES",
    "ChunkRecord",
    "ExtractedDocument",
    "ExtractionError",
    "ExtractionFailure",
    "ExtractionFailureSummary",
    "ExtractionRunResult",
    "ExtractionStatus",
    "PendingFileRecord",
    "RawChunk",
    "extract_file",
    "extract_pending_files",
    "load_extraction_status",
]
